spring:
  application:
    name: userMS-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haiy?useSSL=false
    username: root
    password: root
server:
  port: 8080
